Repository Shuttlerock/trailer, pull requests merged in 2020-09, with the labels that each got.

#2 Add tests
  lib/trailer/concern.rb
  lib/trailer/configuration.rb
  lib/trailer/recorder.rb
  lib/trailer/storage/cloud_watch.rb
  lib/trailer/storage/null.rb
  spec/spec_helper.rb
  spec/trailer/concern_spec.rb
  spec/trailer/configuration_spec.rb
  spec/trailer/middleware/rack_spec.rb
  spec/trailer/middleware/sidekiq_spec.rb
  spec/trailer/recorder_spec.rb
  spec/trailer/storage/cloud_watch_spec.rb
  spec/trailer/utility_spec.rb
  spec/trailer_spec.rb
Labels: big-pr, passed-review

#3 Attach all known data to exceptions
  lib/trailer/recorder.rb
  spec/trailer/recorder_spec.rb
Labels: passed-review

#4 Allow tracing without providing a block
  README.md
  lib/trailer/concern.rb
  spec/trailer/concern_spec.rb
Labels: please-review

#5 Fail gracefully if there's no trace in progress
  lib/trailer/concern.rb
  spec/trailer/concern_spec.rb
Labels: please-review
